Repository SAP/terraform-exporter-btp, pull requests merged in 2024-11, with the labels that each got.

#164 chore: Updated reuse badge url to repo url
  README.md
Labels: ignore-for-release

#166 chore: Add Badges and Links
  .wordlist.txt
  README.md
Labels: documentation

#167 docs: disclaimer for public repo
  README.md
Labels: documentation, ignore-for-release

#168 chore: add links to exclude from check
  .lycheeignore
Labels: internal, ignore-for-release

#175 refactor: reduce cyclomatic finding of import provider factory
  pkg/tfimportprovider/tfImportProviderFactory.go
Labels: internal, ignore-for-release, refactoring

#171 refactor: reduce cyclomatic finding tfconfig
  pkg/tfutils/tfConfig.go
Labels: internal, ignore-for-release, refactoring

#178 chore: refine testcoverage setting
  sonar-project.properties
Labels: internal, ignore-for-release

#176 refactor: reduce cyclomativ finding of tfimport
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release, refactoring

#179 chore: Update release action
  .github/workflows/create-gh-page.yml
  .github/workflows/release.yml
Labels: internal, ignore-for-release

#181 feat: add support for import of cloud foundry users
  cmd/createJson.go
  cmd/exportByResource.go
  pkg/tfimportprovider/cloudfoundryUserImportProvider.go
  pkg/tfimportprovider/cloudfoundryUserImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#184 feat: Add support for import of cloudfoundry_domain
  pkg/tfimportprovider/cloudFoundryDomainImportProvider.go
  pkg/tfimportprovider/cloudFoundryDomainImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#187 fix: issues in exporter binary
  go.mod
  go.sum
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfDocs_test.go
Labels: bug, improvement
