Repository SAP/terraform-exporter-btp, pull requests merged in 2024-12, with the labels that each got.

#195 feat: added support for exporting cloudfoundry_routes
  pkg/tfimportprovider/cloudFoundryRouteImportProvider.go
  pkg/tfimportprovider/cloudFoundryRouteImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#196 feat: added support for importing cloudfoundry_space_quota
  pkg/tfimportprovider/cloudFoundryDomainImportProvider.go
  pkg/tfimportprovider/cloudFoundryRouteImportProvider.go
  pkg/tfimportprovider/cloudFoundrySpaceQuotaImportProvider.go
  pkg/tfimportprovider/cloudFoundrySpaceQuotaImportProvider_test.go
  pkg/tfimportprovider/cloudfoundrySpaceImportProvider.go
  pkg/tfimportprovider/cloudfoundryUserImportProvider.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#194 fix: role collection name handling
  pkg/tfimportprovider/directoryEntitlementImportProvider.go
  pkg/tfimportprovider/directoryEntitlementImportProvider_test.go
  pkg/tfimportprovider/directoryImportProvider.go
  pkg/tfimportprovider/directoryImportProvider_test.go
  pkg/tfimportprovider/directoryRoleCollectionImportProvider.go
  pkg/tfimportprovider/directoryRoleCollectionImportProvider_test.go
  pkg/tfimportprovider/directoryRoleImportProvider.go
  pkg/tfimportprovider/directoryRoleImportProvider_test.go
  pkg/tfimportprovider/subaccountEntitlementImportProvider.go
  pkg/tfimportprovider/subaccountEntitlementImportProvider_test.go
  pkg/tfimportprovider/subaccountImportProvider.go
  pkg/tfimportprovider/subaccountImportProvider_test.go
  pkg/tfimportprovider/subaccountRoleCollectionImportProvider.go
  pkg/tfimportprovider/subaccountRoleCollectionImportProvider_test.go
  pkg/tfimportprovider/subaccountRoleImportProvider.go
  pkg/tfimportprovider/subaccountRoleImportProvider_test.go
  pkg/tfimportprovider/subaccountSecuritySettingImportProvider.go
  pkg/tfimportprovider/subaccountSecuritySettingImportProvider_test.go
  pkg/tfimportprovider/subaccountServiceBindingImportProvider.go
  pkg/tfimportprovider/subaccountServiceBindingImportProvider_test.go
  pkg/tfimportprovider/subaccountServiceInstanceImportProvider.go
  pkg/tfimportprovider/subaccountServiceInstanceImportProvider_test.go
  pkg/tfimportprovider/subaccountSubscriptionImportProvider.go
  pkg/tfimportprovider/subaccountSubscriptionImportProvider_test.go
  pkg/tfimportprovider/subaccountTrustConfigImportProvider.go
  pkg/tfimportprovider/subaccountTrustConfigImportProvider_test.go
Labels: bug, breaking-change

#199 feat: added support for importing cloudfoundry_service_instance
  pkg/tfimportprovider/cloudFoundryServiceInstanceImportProvider.go
  pkg/tfimportprovider/cloudFoundryServiceInstanceImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#210 fix: show config directory to be deleted
  pkg/tfutils/tfConfig.go
Labels: bug

#213 docs: add import limitations
  docs/limitations.md
  docs/prerequisites.md
  mkdocs.yml
Labels: documentation

#215 chore: global update of go dependencies
  go.mod
  go.sum
Labels: dependencies, go
