Repository SAP/terraform-exporter-btp, pull requests merged in 2025-01, with the labels that each got.

#218 chore: update year references
  .reuse/dep5
  README.md
  cmd/createJson.go
  cmd/exportByJson.go
  mkdocs.yml
Labels: ignore-for-release

#220 fix: missing auth validation
  pkg/tfutils/tfConfig.go
Labels: bug

#222 chore: update sonar cloud setting
  sonar-project.properties
Labels: internal

#223 chore: update deprecated sonar cloud action
  .github/workflows/test.yml
Labels: internal, ignore-for-release

#224 chore: update Terraform to latest
  .github/workflows/codeql.yml
  guidelines/DEVELOPER-GUIDE.md
  pkg/tfutils/tfImport.go
Labels: dependencies, ignore-for-release

#225 chore: prep release
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: internal, ignore-for-release

#226 feat: added support for importing cloudfoundry_org_roles
  pkg/output/format.go
  pkg/tfimportprovider/cloudFoundryOrgRoleImportProvider.go
  pkg/tfimportprovider/cloudFoundryOrgRoleImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfImport.go
Labels: enhancement

#229 fix: download of path to coverage report
  .github/workflows/test.yml
  README.md
Labels: ignore-for-release, test setup

#231 test: refine sonar cloud setup
  pkg/files/fileIo_test.go
  pkg/output/format_test.go
  sonar-project.properties
Labels: ignore-for-release, test setup

#232 test: sonar cloud
  sonar-project.properties
Labels: ignore-for-release, test setup

#233 test: add unit tests for tfConfig
  pkg/tfutils/tfConfig_test.go
Labels: ignore-for-release, test setup

#234 test: basic setup of integration test
  .github/workflows/exporter-ci.yml
  .github/workflows/integration-test.yml
  .wordlist.txt
  integration-test/INTEGRATIONTEST.md
  integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json
  integration-test/exporter-reference-data/import-by-json/integrationTestDirectoryCurated.json
  integration-test/exporter-reference-data/import-by-json/integrationTestSubaccountCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestDirectoryReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json
  integration-test/sample-setup/configs.tm.hcl
  integration-test/sample-setup/imports.tm.hcl
  integration-test/sample-setup/stacks/btp_dev/.terraform.lock.hcl
  integration-test/sample-setup/stacks/btp_dev/_terramate_generated_main.tf
  integration-test/sample-setup/stacks/btp_dev/_terramate_generated_provider.tf
  integration-test/sample-setup/stacks/btp_dev/_terramate_generated_variables.tf
  integration-test/sample-setup/stacks/btp_dev/sharing_dev_output_config.tm
  integration-test/sample-setup/stacks/btp_dev/sharing_generated.tf
  integration-test/sample-setup/stacks/btp_dev/stack.tm.hcl
  integration-test/sample-setup/stacks/cloudfoundry_dev/.terraform.lock.hcl
  integration-test/sample-setup/stacks/cloudfoundry_dev/_terramate_generated_main.tf
  integration-test/sample-setup/stacks/cloudfoundry_dev/_terramate_generated_provider.tf
  integration-test/sample-setup/stacks/cloudfoundry_dev/_terramate_generated_variables.tf
  integration-test/sample-setup/stacks/cloudfoundry_dev/sharing_dev_input_config.tm
  integration-test/sample-setup/stacks/cloudfoundry_dev/sharing_generated.tf
  integration-test/sample-setup/stacks/cloudfoundry_dev/stack.tm.hcl
  integration-test/sample-setup/stacks/deploy.tm
  integration-test/sample-setup/stacks/plan.tm
  integration-test/sample-setup/stacks/teardown.tm
  integration-test/sample-setup/templates/generate_main_btp.tm.hcl
  integration-test/sample-setup/templates/generate_main_cf.tm.hcl
  integration-test/sample-setup/templates/generate_provider_btp.tm.hcl
  integration-test/sample-setup/templates/generate_provider_cf.tm.hcl
  integration-test/sample-setup/templates/generate_variables_btp.tm.hcl
  integration-test/sample-setup/templates/generate_variables_cf.tm.hcl
  integration-test/sample-setup/terramate.tm
Labels: ignore-for-release, test setup

#244 chore: gh action go setup
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ignore-for-release, test setup

#242 feat: add user agent for exporter
  pkg/tfutils/tfImport.go
Labels: enhancement

#248 chore: assign issue/pr to central project
  .github/workflows/assign-project.yml
Labels: internal, ignore-for-release

#246 chore: remove sso login option
  .devcontainer/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  .vscode/launch.json
  assets/devguide-pics/debug0b.png
  docs/prerequisites.md
  guidelines/DEVELOPER-GUIDE.md
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfConfig_test.go
Labels: breaking-change
