Repository SAP/terraform-exporter-btp, pull requests merged in 2025-06, with the labels that each got.

#402 chore: Add installer documentation
  .wordlist.txt
  docs/install.md
  mkdocs.yml
Labels: documentation

#406 chore: change integration test setup for more resillience
  .github/scripts/compareJson.js
  .github/scripts/package-lock.json
  .github/scripts/package.json
  .github/workflows/integration-test.yml
  .gitignore
Labels: internal, ignore-for-release

#409 chore: integration test for release
  .github/workflows/release.yml
Labels: internal, ignore-for-release

#411 refactor: Integration test setup
  .github/workflows/integration-test.yml
  .github/workflows/release.yml
  .github/workflows/update-brew-formula.yaml
Labels: internal, ignore-for-release, refactoring

#413 chore: winget bug-fix
  .github/workflows/publish-winget-package.yaml
Labels: internal, ignore-for-release

#415 chore: Add choco docs
  .wordlist.txt
  Makefile
  choco/tools/chocolateyInstall.ps1
  docs/install.md
Labels: documentation

#424 chore: update opentofu version in dev containers
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
Labels: internal, ignore-for-release
