Repository SAP/terraform-exporter-btp, pull requests merged in 2025-02, with the labels that each got.

#238 test: setup of integration test
  .github/scripts/compareJson.js
  .github/scripts/package.json
  .github/workflows/integration-test.yml
  .wordlist.txt
  integration-test/INTEGRATIONTEST.md
  integration-test/exporter-reference-data/import-by-json/integrationTestDirectoryCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestDirectoryReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json
Labels: ignore-for-release, test setup

#250 chore: pr default automation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/assign-issue-to-project.yml
  .github/workflows/set-default-values-pr.yml
Labels: internal, ignore-for-release

#251 chore: release automation setup
  .github/workflows/assign-issue-to-project.yml
  .github/workflows/pre-release-check.yml
  .github/workflows/release.yml
Labels: ignore-for-release, github_actions

#252 chore: add default labels based on PR title
  .github/workflows/set-default-values-pr.yml
Labels: internal, ignore-for-release

#253 docs: fix link to authentication information
  cmd/root.go
Labels: documentation

#265 feat: firt iteration of Terraform config cleanup
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  docs/tfcodeimprovements.md
  go.mod
  go.sum
  mkdocs.yml
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfcleanup/provider_processor/provider_processor.go
  pkg/tfcleanup/provider_processor/provider_types.go
  pkg/tfcleanup/resource_processor/directory_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
  pkg/tfcleanup/resource_processor/subaccount_entitlement_processor.go
  pkg/tfcleanup/resource_processor/subaccount_processor.go
  pkg/tfcleanup/resource_processor/subaccount_subscription_processor.go
  pkg/tfcleanup/resource_processor/types_directory.go
  pkg/tfcleanup/resource_processor/types_entitlements.go
  pkg/tfcleanup/resource_processor/types_generic.go
  pkg/tfcleanup/resource_processor/types_subaccount.go
  pkg/tfcleanup/resource_processor/types_subscriptions.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfConfig_test.go
Labels: enhancement

#255 feat: added support for importing cf space roles
  cmd/CreateJsonHelper.go
  cmd/createJson.go
  cmd/exportByJson.go
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  cmd/exportCommon.go
  go.mod
  go.sum
  pkg/cfcli/client.go
  pkg/cfcli/session.go
  pkg/files/fileIo.go
  pkg/output/format.go
  pkg/tfimportprovider/cloudFoundrySpaceRoleImportProvider.go
  pkg/tfimportprovider/cloudFoundrySpaceRoleImportProvider_test.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfImport.go
  pkg/tfutils/tfImport_test.go
Labels: enhancement

#268 feat: replace org ID with var
  .vscode/launch.json
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  docs/tfcodeimprovements.md
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfcleanup/resource_processor/btp_directory_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go
  pkg/tfcleanup/resource_processor/cloudfoundry_org_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
  pkg/tfcleanup/resource_processor/types_btp_directory.go
  pkg/tfcleanup/resource_processor/types_btp_entitlements.go
  pkg/tfcleanup/resource_processor/types_btp_subaccount.go
  pkg/tfcleanup/resource_processor/types_btp_subscriptions.go
  pkg/tfcleanup/resource_processor/types_cloudfoundry.go
Labels: enhancement

#270 chore: update reference data for integration test
  integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
Labels: internal, ignore-for-release

#271 feat: resolve entitlement service instance dependency
  docs/tfcodeimprovements.md
  internal/btpcli/facade.go
  internal/btpcli/facade_services.go
  internal/btpcli/facade_services_offering.go
  internal/btpcli/facade_services_offering_test.go
  internal/btpcli/types/servicemanager/model_service_offering_metadata.go
  internal/btpcli/types/servicemanager/model_service_offering_response_list.go
  internal/btpcli/types/servicemanager/model_service_offering_response_object.go
  internal/btpcli/wrapper.go
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
  pkg/tfcleanup/resource_processor/types_btp_service_instance.go
Labels: enhancement

#276 chore: update cf provider version to 1.3.0
  pkg/tfimportprovider/cloudFoundrySpaceRoleImportProvider.go
  pkg/tfutils/tfConfig_test.go
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#278 feat: trust config cleanup
  cmd/CreateJsonHelper.go
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  docs/tfcodeimprovements.md
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfcleanup/provider_processor/provider_processor.go
  pkg/tfcleanup/provider_processor/provider_types.go
  pkg/tfcleanup/resource_processor/btp_directory_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_trust_configuration_processor.go
  pkg/tfcleanup/resource_processor/cloudfoundry_org_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
  pkg/tfcleanup/resource_processor/types_btp_directory.go
  pkg/tfcleanup/resource_processor/types_btp_entitlements.go
  pkg/tfcleanup/resource_processor/types_btp_service_instance.go
  pkg/tfcleanup/resource_processor/types_btp_subaccount.go
  pkg/tfcleanup/resource_processor/types_btp_subscriptions.go
  pkg/tfcleanup/resource_processor/types_cloudfoundry.go
  pkg/tfcleanup/resource_processor/types_generic.go
Labels: enhancement

#285 chore: bump dependency Terraform provider
  .github/ISSUE_TEMPLATE/bug_report.yml
  guidelines/DEVELOPER-GUIDE.md
  integration-test/sample-setup/configs.tm.hcl
  integration-test/sample-setup/stacks/btp_dev/.terraform.lock.hcl
  integration-test/sample-setup/stacks/btp_dev/_terramate_generated_provider.tf
  integration-test/sample-setup/stacks/cloudfoundry_dev/.terraform.lock.hcl
  integration-test/sample-setup/stacks/cloudfoundry_dev/_terramate_generated_provider.tf
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#287 chore: fix goreleaser warning
  .goreleaser.yml
Labels: internal, ignore-for-release

#288 chore: upgrade to latest go version
  README.md
  go.mod
Labels: internal, ignore-for-release

#289 feat: code reusability - add space dependency for CF resources
  internal/cfcli/client.go
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/resource_processor/cloudfoundry_space_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
Labels: enhancement

#290 test: add tests for TF cleanup logic
  internal/btpcli/wrapper.go
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfcleanup/generic_tools/generic_tools_test.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfcleanup/provider_processor/provider_process_test.go
  pkg/tfcleanup/resource_processor/btp_role_collection_processor_test.go
  pkg/tfcleanup/resource_processor/btp_role_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_trust_configuration_processor_test.go
  pkg/tfcleanup/resource_processor/cloudfoundry_org_processor.go
  pkg/tfcleanup/resource_processor/cloudfoundry_space_processor.go
  pkg/tfcleanup/resource_processor/cloudfoundry_space_processor_test.go
  pkg/tfcleanup/resource_processor/resource_processor.go
  pkg/tfcleanup/testutils/test_helper.go
  pkg/tfcleanup/testutils/testdata/provider_btp_source.tf
  pkg/tfcleanup/testutils/testdata/provider_btp_target.tf
  pkg/tfcleanup/testutils/testdata/provider_cf_source.tf
  pkg/tfcleanup/testutils/testdata/provider_cf_target.tf
  pkg/tfcleanup/testutils/testdata/remove_config_block_source.tf
  pkg/tfcleanup/testutils/testdata/remove_config_block_target.tf
  pkg/tfcleanup/testutils/testdata/remove_import_block_source.tf
  pkg/tfcleanup/testutils/testdata/remove_import_block_target.tf
  pkg/tfcleanup/testutils/testdata/resource_cf_space_dependency_source.tf
  pkg/tfcleanup/testutils/testdata/resource_cf_space_dependency_target.tf
  pkg/tfcleanup/testutils/testdata/resource_cf_space_no_dependency.tf
  pkg/tfcleanup/testutils/testdata/resource_empty_attributes_source.tf
  pkg/tfcleanup/testutils/testdata/resource_empty_attributes_target.tf
  pkg/tfcleanup/testutils/testdata/resource_main_dependency_source.tf
  pkg/tfcleanup/testutils/testdata/resource_main_dependency_target.tf
  pkg/tfcleanup/testutils/testdata/resource_replace_attribute_source.tf
  pkg/tfcleanup/testutils/testdata/resource_replace_attribute_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_entitlement.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_entitlement_incomplete.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_collection_dep_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_collection_dep_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_collection_no_dependency.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_collection_single_dep_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_collection_single_dep_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_role_incomplete.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_service_instance_dep_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_service_instance_dep_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_service_instance_no_dependency.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_subscription_dep_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_subscription_dep_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_subscription_no_dependency.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_trust_configuration_no_replace.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_trust_configuration_replace.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_with_ga_parent_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_with_ga_parent_target.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_wo_ga_parent_source.tf
  pkg/tfcleanup/testutils/testdata/resource_subaccount_wo_ga_parent_target.tf
  sonar-project.properties
Labels: internal, ignore-for-release, test setup

#292 chore: upgrade devcontainer to Golang 1.24
  .devcontainer/default-opentofu/devcontainer.json
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile-opentofu/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
Labels: internal, ignore-for-release

#295 feat: make code cleanup default
  docs/tfcodeimprovements.md
  pkg/tfcleanup/orchestrator/orchestrator.go
Labels: enhancement
