Repository SAP/terraform-exporter-btp, pull requests merged in 2025-03, with the labels that each got.

#299 docs: refine next steps document
  pkg/output/output.go
Labels: documentation

#301 feat: support injection of backend configurations
  .wordlist.txt
  cmd/exportByJson.go
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  docs/btptf.md
  docs/remotebackend.md
  mkdocs.yml
  pkg/output/output.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfcleanup/provider_processor/provider_process_test.go
  pkg/tfcleanup/provider_processor/provider_processor.go
  pkg/tfcleanup/testutils/test_helper.go
  pkg/tfcleanup/testutils/testdata/backend.tf
  pkg/tfcleanup/testutils/testdata/provider_btp_backend_source.tf
  pkg/tfcleanup/testutils/testdata/provider_btp_backend_target.tf
  pkg/tfcleanup/testutils/testdata/provider_btp_wo_backend.tf
  pkg/tfutils/tfBackend.go
  pkg/tfutils/tfConfig.go
Labels: enhancement

#304 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: internal, ignore-for-release

#306 feat: resume failed export runs
  .wordlist.txt
  cmd/exportByJsonHelper.go
  cmd/exportByResource.go
  docs/concepts.md
  docs/gettingstarted.md
  docs/img/export-failed.png
  docs/img/incomplete-export-files.png
  docs/img/incomplete-export-log.png
  docs/img/resume-result-files.png
  docs/img/resume-step1.png
  docs/img/resume-step2.png
  docs/img/resumed-export-result.png
  docs/resume.md
  go.mod
  go.sum
  mkdocs.yml
  pkg/resume/exportlog.go
  pkg/tfutils/tfConfig.go
  sonar-project.properties
Labels: enhancement

#307 docs: fix layout of resume doc
  docs/resume.md
Labels: documentation, ignore-for-release

#308 docs: formatting
  docs/resume.md
Labels: documentation, ignore-for-release

#310 fix(breaking-change): remove cloudfoundry_users from export
  docs/limitations.md
  pkg/tfutils/tfConfig.go
Labels: bug, breaking-change

#311 feat: version output
  cmd/root.go
  docs/btptf.md
Labels: enhancement

#314 test: recording of updated reference data
  integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json
Labels: internal, ignore-for-release, test setup

#315 docs: update version information
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
Labels: documentation

#316 chore: fix markdown issue
  README.md
Labels: internal, ignore-for-release

#317 chore: refinement of docs and command help
  cmd/exportByJson.go
  cmd/exportByResource.go
  docs/btptf.md
  mkdocs.yml
Labels: internal, ignore-for-release

#318 fix: failing build on Windows
  go.mod
  go.sum
  pkg/tfutils/tfConfig.go
Labels: bug

#319 chore: validate source code builds on Windows
  .github/workflows/validate_build_win.yml
Labels: internal, ignore-for-release

#320 chore: update Terraform provider version
  .github/workflows/integration-test.yml
  guidelines/DEVELOPER-GUIDE.md
  integration-test/sample-setup/configs.tm.hcl
  integration-test/sample-setup/stacks/btp_dev/_terramate_generated_provider.tf
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#322 docs: refinement of inline documentationa and docs
  cmd/createJson.go
  cmd/exportByJson.go
  cmd/exportByResource.go
  cmd/root.go
  docs/btptf.md
  docs/concepts.md
  docs/index.md
  docs/install.md
  docs/limitations.md
  docs/prerequisites.md
Labels: documentation, breaking-change

#323 docs: inline app help
  cmd/exportByJson.go
  cmd/exportByResource.go
  docs/btptf.md
Labels: documentation

#324 feat: clickable output target
  cmd/createJson.go
  cmd/exportByJson.go
  cmd/exportByResource.go
  cmd/root.go
  docs/btptf.md
  pkg/files/fileIo.go
  pkg/output/output.go
Labels: enhancement

#327 chore: prep release candidate
  .github/ISSUE_TEMPLATE/bug_report.yml
  README.md
Labels: internal, ignore-for-release

#328 docs: align inline documentation with temporal limitations
  cmd/createJson.go
  cmd/exportByResource.go
Labels: documentation

#331 feat: filter default role collections from export
  docs/tfcodeimprovements.md
  docs/troubleshooting.md
  internal/btpcli/facade.go
  internal/btpcli/facade_security.go
  internal/btpcli/facade_security_role_collection.go
  internal/btpcli/facade_security_role_collection_test.go
  internal/btpcli/types/xsuaa_authz/model_attribute_reference.go
  internal/btpcli/types/xsuaa_authz/model_group_reference.go
  internal/btpcli/types/xsuaa_authz/model_role.go
  internal/btpcli/types/xsuaa_authz/model_role_attribute.go
  internal/btpcli/types/xsuaa_authz/model_role_collection.go
  internal/btpcli/types/xsuaa_authz/model_role_collection_attribute.go
  internal/btpcli/types/xsuaa_authz/model_role_collection_description.go
  internal/btpcli/types/xsuaa_authz/model_role_collection_reference.go
  internal/btpcli/types/xsuaa_authz/model_role_reference.go
  internal/btpcli/types/xsuaa_authz/model_role_template.go
  internal/btpcli/types/xsuaa_authz/model_role_update.go
  internal/btpcli/types/xsuaa_authz/model_saml_attr_assignment.go
  internal/btpcli/types/xsuaa_authz/model_scope.go
  internal/btpcli/types/xsuaa_authz/model_user_reference.go
  internal/btpcli/wrapper.go
  mkdocs.yml
  pkg/defaultfilter/defaultfilter.go
  pkg/tfcleanup/orchestrator/orchestrator.go
  pkg/tfimportprovider/directoryRoleCollectionImportProvider.go
  pkg/tfimportprovider/subaccountRoleCollectionImportProvider.go
  pkg/tfutils/tfImport.go
  pkg/tfutils/tfWrapper.go
  pkg/toggles/toggles.go
Labels: enhancement

#337 chore: update test recording
  .github/workflows/integration-test.yml
  cmd/root.go
  integration-test/exporter-reference-data/import-by-json/integrationTestDirectoryCurated.json
  integration-test/exporter-reference-data/import-by-json/integrationTestSubaccountCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestDirectoryReference.json
  integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json
  sonar-project.properties
Labels: internal, ignore-for-release

#340 chore: update code to align mit golint v2
  cmd/cmdMarkdownHelper.go
  cmd/exportByJsonHelper.go
  cmd/exportCommon.go
  internal/btpcli/client_test.go
  internal/btpcli/helper.go
  pkg/files/fileIo.go
  pkg/output/format.go
  pkg/tfcleanup/generic_tools/generic_tools.go
  pkg/tfimportprovider/cloudFoundryDomainImportProvider.go
  pkg/tfimportprovider/cloudFoundryOrgRoleImportProvider.go
  pkg/tfimportprovider/cloudFoundryRouteImportProvider.go
  pkg/tfimportprovider/cloudFoundryServiceInstanceImportProvider.go
  pkg/tfimportprovider/cloudFoundrySpaceQuotaImportProvider.go
  pkg/tfimportprovider/cloudFoundrySpaceRoleImportProvider.go
  pkg/tfimportprovider/cloudfoundrySpaceImportProvider.go
  pkg/tfimportprovider/cloudfoundryUserImportProvider.go
  pkg/tfimportprovider/directoryEntitlementImportProvider.go
  pkg/tfimportprovider/directoryImportProvider.go
  pkg/tfimportprovider/directoryRoleCollectionImportProvider.go
  pkg/tfimportprovider/directoryRoleImportProvider.go
  pkg/tfimportprovider/subaccountEntitlementImportProvider.go
  pkg/tfimportprovider/subaccountEnvInstanceImportProvider.go
  pkg/tfimportprovider/subaccountImportProvider.go
  pkg/tfimportprovider/subaccountRoleCollectionImportProvider.go
  pkg/tfimportprovider/subaccountRoleImportProvider.go
  pkg/tfimportprovider/subaccountSecuritySettingImportProvider.go
  pkg/tfimportprovider/subaccountServiceBindingImportProvider.go
  pkg/tfimportprovider/subaccountServiceInstanceImportProvider.go
  pkg/tfimportprovider/subaccountSubscriptionImportProvider.go
  pkg/tfimportprovider/subaccountTrustConfigImportProvider.go
  pkg/tfimportprovider/tfImportProviderFactory.go
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfConfig_test.go
  pkg/tfutils/tfDocs.go
  pkg/tfutils/tfDocs_test.go
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#341 docs: update docs
  cmd/cmdMarkdownHelper.go
  docs/btptf.md
Labels: documentation

#344 docs: fix formating issues in generated docs
  docs/concepts.md
  docs/gettingstarted.md
  docs/install.md
Labels: documentation

#345 chore: Create update-brew-formula.yaml
  .github/workflows/update-brew-formula.yaml
Labels: internal, ignore-for-release

#346 docs: update support section and refine NextSteps.md
  docs/gettingstarted.md
  docs/index.md
  pkg/output/output.go
Labels: documentation

#347 chore: Add Homebrew build action
  .github/scripts/update-btptf-brew-formula.sh
  .github/workflows/update-brew-formula.yaml
  btptf.rb
Labels: internal, ignore-for-release

#349 chore: Add permissions
  .github/workflows/update-brew-formula.yaml
Labels: internal, ignore-for-release

#352 chore: update CF provider version
  .github/workflows/issue-comment-created.yml
  integration-test/sample-setup/configs.tm.hcl
  integration-test/sample-setup/stacks/cloudfoundry_dev/.terraform.lock.hcl
  integration-test/sample-setup/stacks/cloudfoundry_dev/_terramate_generated_provider.tf
  pkg/tfcleanup/testutils/testdata/provider_cf_source.tf
  pkg/tfcleanup/testutils/testdata/provider_cf_target.tf
  pkg/tfutils/tfConfig_test.go
  pkg/tfutils/tfDocs_test.go
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#353 fix: import of Cloud Foundry users
  cmd/createJson.go
  cmd/exportByResource.go
  integration-test/exporter-reference-data/import-by-json/integrationTestCfOrgCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestCfOrgReference.json
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfImport.go
Labels: bug

#354 chore: refine code for JSON filtering
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#356 feat: filter default entitlements for subaccount
  docs/tfcodeimprovements.md
  docs/troubleshooting.md
  integration-test/exporter-reference-data/import-by-json/integrationTestSubaccountCurated.json
  integration-test/exporter-reference-data/json-inventory/integrationTestSubaccountReference.json
  pkg/defaultfilter/defaultfilter.go
  pkg/defaultfilter/types_defaultfilter.go
  pkg/tfimportprovider/subaccountEntitlementImportProvider.go
  pkg/tfimportprovider/subaccountEntitlementImportProvider_test.go
  pkg/tfutils/tfImport.go
  pkg/toggles/toggles.go
Labels: enhancement
