Repository SAP/terraform-exporter-btp, pull requests merged in 2025-04, with the labels that each got.

#359 docs: update README.md for GA
  README.md
Labels: documentation

#362 fix: issue when SSO Environment parameter ist set
  docs/prerequisites.md
  pkg/tfutils/tfConfig.go
  pkg/tfutils/tfConfig_test.go
Labels: bug

#368 chore: Update CF version
  pkg/tfutils/tfConfig_test.go
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release
