Repository SAP/terraform-exporter-btp, pull requests merged in 2025-05, with the labels that each got.

#369 chore: verion update of TF provider BTP
  pkg/tfutils/tfImport.go
Labels: internal, ignore-for-release

#372 feat: dependency management of commercial app name
  internal/btpcli/facade_accounts.go
  internal/btpcli/facade_accounts_subscription.go
  internal/btpcli/facade_accounts_subscription_test.go
  internal/btpcli/types/saas_manager_service/model_entitled_applications_error_response_object.go
  internal/btpcli/types/saas_manager_service/model_entitled_applications_response_object.go
  internal/btpcli/types/saas_manager_service/model_timestamp.go
  internal/btpcli/types/saas_manager_service/time.go
  internal/btpcli/wrapper.go
  pkg/tfcleanup/generic_tools/generic_types.go
  pkg/tfcleanup/resource_processor/btp_role_collection_processor.go
  pkg/tfcleanup/resource_processor/btp_role_collection_processor_test.go
  pkg/tfcleanup/resource_processor/btp_role_processor.go
  pkg/tfcleanup/resource_processor/btp_role_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_entitlement_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_service_instance_processor_test.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor.go
  pkg/tfcleanup/resource_processor/btp_subaccount_subscription_processor_test.go
  pkg/tfcleanup/resource_processor/cloudfoundry_space_processor.go
  pkg/tfcleanup/resource_processor/resource_processor.go
Labels: enhancement

#379 fix: Space resource name creation
  pkg/tfimportprovider/cloudfoundrySpaceImportProvider.go
  pkg/tfimportprovider/cloudfoundrySpaceImportProvider_test.go
Labels: bug

#380 fix: creation of duplicate data sources
  pkg/tfcleanup/resource_processor/resource_processor.go
Labels: bug

#381 fix: services instances in CF get imported as BTP resource
  pkg/defaultfilter/defaultfilter.go
  pkg/tfimportprovider/subaccountServiceInstanceImportProvider.go
  pkg/tfimportprovider/subaccountServiceInstanceImportProvider_test.go
  pkg/tfutils/tfImport.go
Labels: bug

#382 chore: prep release 1.1.0
  cmd/root.go
Labels: internal, ignore-for-release

#386 docs: typo in code samples
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/gettingstarted.md
Labels: documentation

#387 docs: typo for code samples
  docs/gettingstarted.md
Labels: documentation

#390 docs: enhance prerequisites for Terraform/OpenTofu CLI
  .wordlist.txt
  docs/prerequisites.md
  docs/troubleshooting.md
Labels: documentation

#397 chore: Choco improvements
  .github/workflows/publish-chocolatey-package.yml
  choco/sap-btptf.nuspec
  choco/tools/chocolateyInstall.ps1
  choco/tools/chocolateyUninstall.ps1
  choco/tools/uninstall.ps1
Labels: internal, ignore-for-release

#398 chore: Add winget action
  .github/workflows/publish-winget-package.yaml
Labels: internal, ignore-for-release

#400 chore: minor fix - choco-action
  .github/workflows/publish-chocolatey-package.yml
Labels: internal, ignore-for-release
